version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQATestPRODGit2807Project
  gitServerName: kusi_AWSStage02
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
services:
- serviceName: project.siqatestprodgit2807.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: SIQATestPRODGit2807Project
    version: "1.0"
- serviceName: project.siqatestprodgit2807.integrations:SIQAAdapterFlow
  packages:
  - name: SIQATestPRODGit2807Project
    version: "1.0"
